"""QuantPlatformKit public package surface."""

__version__ = "0.7.11"

from .common.models import (
    ExecutionReport,
    OrderIntent,
    PortfolioSnapshot,
    Position,
    PricePoint,
    PriceSeries,
    QuoteSnapshot,
    StrategyDecision,
)
from .common.strategy_contracts import (
    AllocationIntent,
    BudgetIntent,
    PositionTarget,
    StrategyContext,
    StrategyContractValidationError,
    StrategyDecision as StrategyContractDecision,
    StrategyEntrypoint,
    StrategyManifest,
    StrategyRuntimeAdapter,
    build_allocation_intent,
    build_allocation_payload,
    build_value_target_allocation_intent,
    validate_strategy_decision,
    validate_strategy_manifest,
    validate_strategy_runtime_adapter,
    build_value_target_plan_payload,
)
from .common.execution_translation import (
    ValueTargetPortfolioInputs,
    build_value_target_portfolio_inputs_from_account_state,
    build_value_target_portfolio_inputs_from_snapshot,
    build_value_target_runtime_plan,
    resolve_decision_target_mode,
    translate_decision_to_target_mode,
    translate_value_decision_to_weight_targets,
    translate_weight_decision_to_value_targets,
)
from .common.runtime_inputs import (
    build_account_state_from_portfolio_snapshot,
    build_portfolio_snapshot_from_account_state,
    build_strategy_evaluation_inputs,
)
from .common.strategies import (
    CRYPTO_DOMAIN,
    PlatformStrategyPolicy,
    StrategyCatalog,
    StrategyDefinition,
    StrategyEntrypointDefinition,
    StrategyMetadata,
    US_EQUITY_DOMAIN,
    build_platform_profile_matrix,
    build_profile_aliases,
    build_strategy_catalog,
    build_strategy_index_rows,
    build_strategy_manifest,
    get_catalog_compatible_platforms,
    get_catalog_strategy_definition,
    get_catalog_strategy_metadata,
    get_enabled_profiles_for_platform,
    load_strategy_entrypoint,
    normalize_profile_name,
    resolve_catalog_profile,
    resolve_platform_strategy_definition,
)

__all__ = [
    "__version__",
    "AllocationIntent",
    "BudgetIntent",
    "CRYPTO_DOMAIN",
    "ExecutionReport",
    "PlatformStrategyPolicy",
    "OrderIntent",
    "PortfolioSnapshot",
    "Position",
    "PositionTarget",
    "PricePoint",
    "PriceSeries",
    "QuoteSnapshot",
    "StrategyCatalog",
    "StrategyContext",
    "StrategyContractDecision",
    "StrategyContractValidationError",
    "StrategyDecision",
    "StrategyDefinition",
    "StrategyEntrypoint",
    "StrategyEntrypointDefinition",
    "StrategyManifest",
    "StrategyMetadata",
    "StrategyRuntimeAdapter",
    "ValueTargetPortfolioInputs",
    "US_EQUITY_DOMAIN",
    "build_allocation_intent",
    "build_allocation_payload",
    "build_account_state_from_portfolio_snapshot",
    "build_portfolio_snapshot_from_account_state",
    "build_strategy_evaluation_inputs",
    "build_value_target_portfolio_inputs_from_account_state",
    "build_value_target_portfolio_inputs_from_snapshot",
    "resolve_decision_target_mode",
    "translate_decision_to_target_mode",
    "translate_value_decision_to_weight_targets",
    "translate_weight_decision_to_value_targets",
    "build_value_target_allocation_intent",
    "build_value_target_plan_payload",
    "build_value_target_runtime_plan",
    "build_platform_profile_matrix",
    "build_profile_aliases",
    "build_strategy_catalog",
    "build_strategy_index_rows",
    "build_strategy_manifest",
    "get_catalog_compatible_platforms",
    "get_catalog_strategy_definition",
    "get_catalog_strategy_metadata",
    "get_enabled_profiles_for_platform",
    "load_strategy_entrypoint",
    "normalize_profile_name",
    "resolve_catalog_profile",
    "resolve_platform_strategy_definition",
    "validate_strategy_decision",
    "validate_strategy_manifest",
    "validate_strategy_runtime_adapter",
]
