"""Shared domain models, ports, strategy contracts, and plugin helpers."""

from .notification_localization import (
    COMMON_ZH_NOTIFICATION_REPLACEMENTS,
    localize_notification_text,
    translator_uses_zh,
)
from .execution_outcomes import (
    DEFAULT_EXECUTION_BLOCKING_SKIP_REASONS,
    DEFAULT_TERMINAL_FUNDING_BLOCK_SKIP_REASONS,
    DEFAULT_TERMINAL_STRATEGY_RUN_STAGES,
    STAGE_COMPLETED,
    STAGE_DRY_RUN_COMPLETED,
    STAGE_EXECUTION_BLOCKED,
    STAGE_FUNDING_BLOCKED,
    STAGE_NO_ACTION,
    STAGE_ORDERS_PLANNED,
    STAGE_PARTIAL_SUBMITTED,
    STAGE_RECONCILED,
    STAGE_SUBMITTED,
    filter_execution_blocking_skips,
    is_terminal_funding_block,
    is_terminal_strategy_run_stage,
    normalize_skip_reason,
    normalize_stage,
    resolve_strategy_run_stage,
)
from .runtime_logging import (
    RuntimeLogContext,
    build_run_id,
    emit_runtime_log,
    extract_cloud_trace,
)
from .runtime_assembly import RuntimeAssembly, build_runtime_assembly
from .runtime_target import (
    build_runtime_context_fields,
    RuntimeTarget,
    build_runtime_target,
    resolve_runtime_target_from_env,
)
from .strategy_plugins import (
    PLUGIN_MODE_SHADOW,
    SUPPORTED_STRATEGY_PLUGIN_MODES,
    StrategyPluginMountConfig,
    StrategyPluginSignal,
    build_strategy_plugin_report_payload,
    load_configured_strategy_plugin_signals,
    load_strategy_plugin_signal,
    normalize_strategy_plugin_mode,
    parse_strategy_plugin_mounts,
    validate_strategy_plugin_signal_payload,
)

__all__ = [
    "COMMON_ZH_NOTIFICATION_REPLACEMENTS",
    "DEFAULT_EXECUTION_BLOCKING_SKIP_REASONS",
    "DEFAULT_TERMINAL_FUNDING_BLOCK_SKIP_REASONS",
    "DEFAULT_TERMINAL_STRATEGY_RUN_STAGES",
    "PLUGIN_MODE_SHADOW",
    "STAGE_COMPLETED",
    "STAGE_DRY_RUN_COMPLETED",
    "STAGE_EXECUTION_BLOCKED",
    "STAGE_FUNDING_BLOCKED",
    "STAGE_NO_ACTION",
    "STAGE_ORDERS_PLANNED",
    "STAGE_PARTIAL_SUBMITTED",
    "STAGE_RECONCILED",
    "STAGE_SUBMITTED",
    "SUPPORTED_STRATEGY_PLUGIN_MODES",
    "filter_execution_blocking_skips",
    "is_terminal_funding_block",
    "is_terminal_strategy_run_stage",
    "localize_notification_text",
    "normalize_skip_reason",
    "normalize_stage",
    "resolve_strategy_run_stage",
    "RuntimeTarget",
    "build_runtime_context_fields",
    "build_run_id",
    "emit_runtime_log",
    "extract_cloud_trace",
    "RuntimeLogContext",
    "RuntimeAssembly",
    "build_runtime_assembly",
    "StrategyPluginMountConfig",
    "StrategyPluginSignal",
    "build_strategy_plugin_report_payload",
    "build_runtime_target",
    "load_configured_strategy_plugin_signals",
    "load_strategy_plugin_signal",
    "normalize_strategy_plugin_mode",
    "parse_strategy_plugin_mounts",
    "resolve_runtime_target_from_env",
    "translator_uses_zh",
    "validate_strategy_plugin_signal_payload",
]
