"""Codex integration bridge — connects strategy_lifecycle to the Codex ecosystem.

Integrates with three existing systems:
- CodexAuditBridge: automated monthly audits + reviewable PR creation
- ai_audit.py (QuantStrategyPlugins): reusable AI audit client (Codex/OpenAI/Anthropic)
- TelegramCodexBot: GitHub issue → Codex session bridge + notifications

This module provides the glue layer that enables unmanned auto-monitoring and
optimization by:
1. Auto-creating GitHub issues when drift reaches REVIEW/CRITICAL
2. Invoking AI-driven optimization decisions via ai_audit.py
3. Generating structured proposals that CodexAuditBridge can turn into PRs
4. Preparing bounded candidate evidence for a human decision
"""

from __future__ import annotations

import json
import os
import subprocess
from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from quant_platform_kit.strategy_lifecycle.contracts import (
    DriftResult,
    DriftStatus,
    StrategyPerformanceSnapshot,
)
from quant_platform_kit.strategy_lifecycle.performance_store import PerformanceStore


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


# ── GitHub Issue Bridge ──────────────────────────────────────────────


@dataclass(frozen=True)
class AutoIssueConfig:
    """Configuration for auto-creating GitHub issues from drift alerts."""

    owner: str = "QuantStrategyLab"
    repo: str = "AuditOrchestrator"
    labels: tuple[str, ...] = ("strategy-lifecycle", "drift-alert", "auto-optimize")
    assignees: tuple[str, ...] = ()
    create_for_statuses: tuple[str, ...] = ("review", "critical")

    @classmethod
    def from_env(cls) -> "AutoIssueConfig":
        return cls(
            owner=os.environ.get("CODEX_AUDIT_ORG", "QuantStrategyLab"),
            repo=os.environ.get("CODEX_AUDIT_ORCHESTRATOR_REPO", "AuditOrchestrator"),
            labels=tuple(
                s.strip()
                for s in os.environ.get("AUTO_ISSUE_LABELS", "strategy-lifecycle,drift-alert,auto-optimize").split(",")
                if s.strip()
            ),
            create_for_statuses=tuple(
                s.strip()
                for s in os.environ.get("AUTO_ISSUE_STATUSES", "review,critical").split(",")
                if s.strip()
            ),
        )


def build_issue_body(
    drift: DriftResult,
    snapshot: StrategyPerformanceSnapshot | None = None,
    *,
    include_metrics: bool = True,
) -> str:
    """Build a structured GitHub issue body from a drift result.

    The format is designed to be machine-readable by CodexAuditBridge
    while remaining human-readable for manual review.
    """
    status_emoji = {"watch": "⚠️", "review": "🔴", "critical": "🚨"}.get(drift.status.value, "❓")

    lines = [
        f"## {status_emoji} Strategy Drift: {drift.strategy_profile}",
        "",
        "> Auto-generated by strategy_lifecycle drift detector.",
        "",
        "```json",
        json.dumps(_drift_issue_metadata(drift, snapshot), ensure_ascii=False, indent=2),
        "```",
        "",
        "### Drift Dimensions",
        "",
        "| Metric | Actual | Expected | Deviation | Threshold | Breached |",
        "| --- | ---: | ---: | ---: | ---: | --- |",
    ]

    for dim in drift.dimensions.values():
        breached = "⚠️ YES" if dim.breached else "✅ no"
        lines.append(
            f"| {dim.metric_name} | {dim.actual:.4f} | {dim.expected:.4f} | "
            f"{dim.deviation_pct:.1%} | {dim.threshold:.1%} | {breached} |"
        )

    lines.extend(
        [
            "",
            f"**Status:** {drift.status.value.upper()}",
            f"**Drift Score:** {drift.drift_score:.3f}",
            f"**Escalated:** {'Yes' if drift.escalated else 'No'}",
            f"**As-of:** {drift.as_of}",
            "",
            "### Recommended Action",
            "",
            _codex_action_directive(drift),
            "",
            "---",
            f"_Generated: {_now_iso()}_",
        ]
    )
    return "\n".join(lines)


def _drift_issue_metadata(drift: DriftResult, snapshot: StrategyPerformanceSnapshot | None) -> dict[str, Any]:
    """Machine-readable metadata block for Codex consumption."""
    return {
        "schema": "strategy_lifecycle_drift_issue.v1",
        "strategy_profile": drift.strategy_profile,
        "domain": drift.domain,
        "as_of": drift.as_of.isoformat(),
        "drift_score": drift.drift_score,
        "status": drift.status.value,
        "escalated": drift.escalated,
        "breached_dimensions": [d.metric_name for d in drift.breached_dimensions],
        "action": "auto_optimize" if drift.status in (DriftStatus.REVIEW, DriftStatus.CRITICAL) else "monitor",
        "snapshot_summary": (
            {
                "sharpe_126": snapshot.windows[126].sharpe_ratio if snapshot and 126 in snapshot.windows else None,
                "sharpe_252": snapshot.windows[252].sharpe_ratio if snapshot and 252 in snapshot.windows else None,
            }
            if snapshot
            else None
        ),
    }


def _codex_action_directive(drift: DriftResult) -> str:
    """Generate the action directive that Codex will parse and execute."""
    if drift.status == DriftStatus.CRITICAL:
        return (
            "**CRITICAL**: Codex should immediately:\n"
            "1. Run `python main.py optimize --strategy {profile}` to search for better parameters\n"
            "2. If improvement found, prepare a parameter update PR via CodexAuditBridge\n"
            "3. Flag for human review before deployment"
        ).format(profile=drift.strategy_profile)
    if drift.status == DriftStatus.REVIEW:
        return (
            "**REVIEW**: Codex should:\n"
            "1. Run parameter optimization for `{profile}`\n"
            "2. Compare proposed vs current parameters\n"
            "3. Record a bound candidate and evidence package for human review\n"
            "4. Create a human-review-required PR; do not auto-merge or deploy"
        ).format(profile=drift.strategy_profile)
    return (
        "**WATCH**: No immediate optimization needed. Continue monitoring."
    )


def _find_open_issue_with_title(*, config: AutoIssueConfig, title: str) -> dict[str, Any] | None:
    """Return an exact-title open issue before creating another drift record.

    A drift may persist for several daily cycles. The lifecycle record must be
    durable, but it must not create one issue per cycle for the same unresolved
    profile and severity. If the lookup is unavailable, the caller fails closed
    instead of risking a duplicate.
    """

    try:
        result = subprocess.run(
            [
                "gh",
                "issue",
                "list",
                "--repo",
                f"{config.owner}/{config.repo}",
                "--state",
                "open",
                "--search",
                f'in:title "{title}"',
                "--limit",
                "100",
                "--json",
                "number,title,url",
            ],
            capture_output=True,
            text=True,
            timeout=30,
            env={**os.environ, "GH_PROMPT": "disabled"},
        )
    except FileNotFoundError:
        return {"error": "gh CLI is not installed; cannot deduplicate issues"}
    except Exception as exc:
        return {"error": f"issue deduplication query failed: {exc}"}

    if result.returncode != 0:
        return {"error": f"issue deduplication query failed: {result.stderr.strip()}"}
    try:
        candidates = json.loads(result.stdout or "[]")
    except json.JSONDecodeError:
        return {"error": "issue deduplication query returned invalid JSON"}
    if not isinstance(candidates, list):
        return {"error": "issue deduplication query returned an invalid payload"}
    for candidate in candidates:
        if isinstance(candidate, Mapping) and candidate.get("title") == title:
            return {
                "issue_url": candidate.get("url"),
                "issue_number": candidate.get("number"),
                "deduplicated": True,
            }
    return None


def create_github_issue(
    drift: DriftResult,
    *,
    snapshot: StrategyPerformanceSnapshot | None = None,
    config: AutoIssueConfig | None = None,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Create a GitHub issue for a drift alert.

    Uses the `gh` CLI to create the issue. Falls back to dry-run logging
    if `gh` is not available.

    Returns:
        Dict with issue_url, issue_number, or dry_run=True indicator.
    """
    config = config or AutoIssueConfig.from_env()
    title = f"[{drift.domain}] Drift {drift.status.value.upper()}: {drift.strategy_profile} (score={drift.drift_score:.2f})"
    body = build_issue_body(drift, snapshot)

    if dry_run:
        return {
            "dry_run": True,
            "title": title,
            "repo": f"{config.owner}/{config.repo}",
            "labels": list(config.labels),
            "body_preview": body[:500],
        }

    existing = _find_open_issue_with_title(config=config, title=title)
    if existing is not None:
        if existing.get("error"):
            return {"error": existing["error"], "title": title}
        return {**existing, "title": title, "repo": f"{config.owner}/{config.repo}"}

    try:
        labels_arg = ",".join(config.labels)
        result = subprocess.run(
            [
                "gh", "issue", "create",
                "--repo", f"{config.owner}/{config.repo}",
                "--title", title,
                "--body", body,
                "--label", labels_arg,
            ],
            capture_output=True,
            text=True,
            timeout=30,
            env={**os.environ, "GH_PROMPT": "disabled"},
        )
        if result.returncode != 0:
            return {"error": "gh command failed", "stderr": result.stderr.strip(), "title": title}

        issue_url = result.stdout.strip()
        return {"issue_url": issue_url, "title": title, "repo": f"{config.owner}/{config.repo}"}
    except FileNotFoundError:
        return {"dry_run": True, "title": title, "note": "gh CLI not installed; dry run only"}
    except Exception as exc:
        return {"error": str(exc), "title": title}


def create_issues_for_domain(
    domain: str,
    *,
    store: PerformanceStore | None = None,
    config: AutoIssueConfig | None = None,
    dry_run: bool = False,
) -> list[dict[str, Any]]:
    """Scan a domain for drifts that need issues and create them.

    Only creates issues for strategies not already covered by an open issue.
    """
    store = store or PerformanceStore.from_env()
    config = config or AutoIssueConfig.from_env()

    from quant_platform_kit.strategy_lifecycle.drift_detector import run_drift_detection

    drifts = run_drift_detection(domain, store=store)
    results: list[dict[str, Any]] = []

    for drift in drifts:
        if drift.status.value not in config.create_for_statuses:
            continue
        if drift.alert_suppressed:
            continue

        snapshot = store.load_latest_snapshot(drift.domain, drift.strategy_profile)
        result = create_github_issue(drift, snapshot=snapshot, config=config, dry_run=dry_run)
        results.append(result)

    return results


# ── AI-Driven Optimization Decision ──────────────────────────────────


@dataclass(frozen=True)
class AiOptimizationContext:
    """Context passed to AI for optimization decision-making."""

    strategy_profile: str
    domain: str
    drift: DriftResult | None = None
    snapshot: StrategyPerformanceSnapshot | None = None
    current_params: Mapping[str, Any] = field(default_factory=dict)

    def to_prompt_context(self) -> str:
        """Render as a structured prompt for AI consumption."""
        parts = [
            f"Strategy: {self.strategy_profile}",
            f"Domain: {self.domain}",
        ]
        if self.drift:
            parts.extend(
                [
                    f"Drift Status: {self.drift.status.value}",
                    f"Drift Score: {self.drift.drift_score:.3f}",
                    "Breached dimensions:",
                ]
            )
            for dim in self.drift.breached_dimensions:
                parts.append(f"  - {dim.metric_name}: actual={dim.actual:.4f}, expected={dim.expected:.4f}")
        if self.snapshot and 126 in self.snapshot.windows:
            w = self.snapshot.windows[126]
            parts.append(f"Live 126d Sharpe: {w.sharpe_ratio:.2f}, CAGR: {w.cagr:.2%}, MaxDD: {w.max_drawdown:.2%}")
        if self.current_params:
            parts.append(f"Current params: {json.dumps(self.current_params)}")
        return "\n".join(parts)


def build_optimization_prompt(context: AiOptimizationContext) -> str:
    """Build a system prompt for AI-driven optimization decision.

    This prompt is designed to be consumed by Codex or any LLM (OpenAI/Anthropic)
    via the ai_audit.py module.
    """
    return f"""You are a quantitative strategy optimization assistant. Your task is to decide whether a strategy needs parameter re-optimization based on drift analysis.

## Context
{context.to_prompt_context()}

## Task
1. Analyze the drift dimensions to determine if optimization is warranted
2. If optimization is needed, suggest which parameters to focus on
3. Recommend the optimization method (grid_search or bayesian)
4. Specify the minimum improvement threshold for acceptance

## Output Format
Respond with a JSON object:
{{
    "optimization_needed": true/false,
    "reason": "brief explanation",
    "focus_dimensions": ["param_name_1", "param_name_2"],
    "recommended_method": "grid_search" | "bayesian",
    "min_improvement_threshold": 0.05,
    "confidence": 0.0-1.0
}}

## Rules
- Only trigger optimization for REVIEW or CRITICAL drift status
- For WATCH status, recommend monitoring only (optimization_needed=false)
- For CRITICAL status, always recommend optimization
- Prefer grid_search for strategies with <5 tunable params, bayesian for >=5
- Set higher min_improvement_threshold (0.08+) for mature strategies with stable parameters
"""


def call_ai_optimization_decision(
    context: AiOptimizationContext,
    *,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Call AiGateway to decide whether optimization is needed.

    Routes through AiGateway (Claude/GPT via LlmAdapter).
    No API keys needed — CODEX_AUDIT_SERVICE_URL only.

    Args:
        context: The optimization context with drift and snapshot data.
        dry_run: If True, return a simulated decision without AI call.

    Returns:
        AI decision dict with optimization_needed, reason, etc.
    """
    if dry_run:
        if context.drift and context.drift.status in (DriftStatus.REVIEW, DriftStatus.CRITICAL):
            return {
                "optimization_needed": True,
                "reason": f"Drift status is {context.drift.status.value}",
                "focus_dimensions": list(context.drift.dimensions.keys()),
                "recommended_method": "grid_search",
                "min_improvement_threshold": 0.05,
                "confidence": 0.8,
            }
        return {
            "optimization_needed": False,
            "reason": "No significant drift detected",
            "recommended_method": "none",
            "min_improvement_threshold": 0.0,
            "confidence": 0.95,
        }

    try:
        from quant_platform_kit.strategy_lifecycle.ai_provider import (
            AiServiceConfig, AiServiceClient, AiProviderConfig,
        )

        config = AiServiceConfig.from_env()
        if not config.reviewers:
            return {"optimization_needed": False, "reason": "No AI backend configured (set CODEX_AUDIT_SERVICE_URL)"}

        client = AiServiceClient(config)
        prompt = build_optimization_prompt(context)
        results = client.review(prompt, timeout=30.0)

        # Use the first successful reviewer result
        for r in results:
            if r.success and r.output:
                import re
                match = re.search(r"\{[\s\S]*\}", r.output)
                if match:
                    return json.loads(match.group(0))
                return {"optimization_needed": False, "reason": "Could not parse AI response", "raw": r.output[:500]}

        return {"optimization_needed": False, "reason": "All AI backends unavailable"}

    except ImportError:
        return call_ai_optimization_decision(context, dry_run=True)
    except Exception as exc:
        return {"optimization_needed": False, "reason": f"AI call failed: {exc}", "error": str(exc)}


# ── Auto-Pilot Orchestration ─────────────────────────────────────────


def _run_monitor_phase(domain: str, store: PerformanceStore) -> list:
    """Phase 1: run performance monitoring."""
    from quant_platform_kit.strategy_lifecycle.performance_monitor import run_monitor
    return run_monitor(domain, store=store)


def _run_drift_phase(domain: str, store: PerformanceStore) -> tuple[list, list]:
    """Phase 2: run drift detection, return (all_drifts, alerting_drifts)."""
    from quant_platform_kit.strategy_lifecycle.drift_detector import run_drift_detection
    drifts = run_drift_detection(domain, store=store)
    alerts = [d for d in drifts if d.status != DriftStatus.HEALTHY and not d.alert_suppressed]
    return drifts, alerts


def _run_issue_phase(domain: str, store: PerformanceStore, dry_run: bool) -> int:
    """Phase 3: create GitHub issues for REVIEW/CRITICAL drifts."""
    from quant_platform_kit.strategy_lifecycle.codex_integration import create_issues_for_domain
    results = create_issues_for_domain(domain, store=store, dry_run=dry_run)
    return len([r for r in results if "issue_url" in r])


def _process_optimization_decision(
    drift: DriftResult,
    store: PerformanceStore,
    dry_run: bool,
) -> dict[str, object]:
    """Phase 4: AI decide → optimize → review → await human decision."""
    from quant_platform_kit.strategy_lifecycle.ai_reviewer import review_proposal, llm_enhanced_review

    snapshot = store.load_latest_snapshot(drift.domain, drift.strategy_profile)
    context = AiOptimizationContext(
        strategy_profile=drift.strategy_profile,
        domain=drift.domain,
        drift=drift,
        snapshot=snapshot,
    )
    decision = call_ai_optimization_decision(context, dry_run=dry_run)
    entry: dict[str, object] = {
        "strategy": drift.strategy_profile,
        "drift_status": drift.status.value,
        "ai_decision": decision,
    }

    if not decision.get("optimization_needed"):
        if dry_run and drift.status in (DriftStatus.REVIEW, DriftStatus.CRITICAL):
            entry["note"] = "Dry run: optimization would be considered"
        return entry

    if dry_run:
        entry["note"] = "Dry run: optimization would be triggered"
        return entry

    try:
        from quant_platform_kit.strategy_lifecycle.param_optimizer import run_optimization

        method = decision.get("recommended_method", "grid_search")
        proposal = run_optimization(
            drift.strategy_profile,
            method=method,
            domain=drift.domain,
            store=store,
        )
        entry["proposal"] = {
            "recommendation": proposal.recommendation,
            "improvement_score": proposal.improvement_score,
        }

        if proposal.recommendation not in ("promote", "needs_review"):
            entry["execution_authorized"] = False
            return entry

        # Rule-based review
        verdict = review_proposal(proposal, drift=drift, snapshot=snapshot)
        entry["ai_review"] = verdict.to_dict()

        if verdict.verdict == "approve":
            entry["execution_authorized"] = False
            entry["requires_human_approval"] = True
            entry["note"] = (
                "Automated review passed; create a bound candidate and obtain "
                "an expiring human decision before any non-live promotion."
            )
        elif verdict.verdict == "escalate":
            llm_v = llm_enhanced_review(proposal, drift=drift, dry_run=dry_run)
            entry["llm_review"] = llm_v.to_dict()
            if llm_v.verdict == "approve":
                entry["execution_authorized"] = False
                entry["escalated_to_human"] = True
                entry["note"] = "LLM review is evidence only; human approval remains required"
            else:
                entry["execution_authorized"] = False
                entry["escalated_to_human"] = True
        else:
            entry["execution_authorized"] = False

    except Exception as exc:
        entry["optimization_error"] = str(exc)

    return entry


def run_auto_pilot_cycle(
    domain: str,
    *,
    store: PerformanceStore | None = None,
    dry_run: bool = False,
    create_issues: bool = True,
    trigger_optimization: bool = True,
) -> dict[str, Any]:
    """Run one complete auto-pilot cycle for a domain.

    Delegates to 4 pipeline phases:
      1. _run_monitor_phase  — run performance monitoring
      2. _run_drift_phase    — run drift detection
      3. _run_issue_phase    — create GitHub issues (optional)
      4. _process_optimization_decision — AI optimize → review → await human decision
    """
    store = store or PerformanceStore.from_env()
    summary: dict[str, Any] = {
        "domain": domain, "cycle_start": _now_iso(),
        "dry_run": dry_run, "actions": [],
    }

    # Phase 1
    snapshots = _run_monitor_phase(domain, store)
    summary["snapshots_count"] = len(snapshots)

    # Phase 2
    drifts, alert_drifts = _run_drift_phase(domain, store)
    summary["drifts_checked"] = len(drifts)
    summary["drifts_alerting"] = len(alert_drifts)

    # Phase 3 (optional)
    if create_issues:
        summary["issues_created"] = _run_issue_phase(domain, store, dry_run)

    # Phase 4 (per drift)
    if trigger_optimization:
        for drift in alert_drifts:
            if drift.status not in (DriftStatus.REVIEW, DriftStatus.CRITICAL):
                continue
            summary["actions"].append(
                _process_optimization_decision(drift, store, dry_run)
            )

    summary["cycle_end"] = _now_iso()
    return summary
