#!/usr/bin/env python3
"""Sync ruff configuration from QPK to a downstream repository.

Usage:
  python scripts/sync_ruff_config.py --target ../QuantUsComboStrategies

Copies ruff-shared.toml from QPK to the target repo and writes a
local .ruff.toml that extends it (no URL dependency).
CI in the target repo always has the config available.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

RUFF_SHARED = "ruff-shared.toml"


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync ruff config to a downstream repo")
    parser.add_argument(
        "--target",
        required=True,
        type=Path,
        help="Path to the target repo root",
    )
    args = parser.parse_args()

    source = Path(__file__).resolve().parent.parent / RUFF_SHARED
    target = args.target.resolve()

    if not source.exists():
        print(f"ERROR: {RUFF_SHARED} not found at {source}", file=sys.stderr)
        return 1

    target_dir = target / RUFF_SHARED
    shutil.copy2(source, target_dir)
    print(f"Copied {RUFF_SHARED} → {target_dir}")

    # Write .ruff.toml that extends the local copy (no URL)
    ruff_toml = target / ".ruff.toml"
    ruff_toml.write_text(
        f"# Auto-generated by sync_ruff_config.py from QuantPlatformKit\n"
        f"extend = \"{RUFF_SHARED}\"\n"
    )
    print(f"Updated {ruff_toml}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
